# Generated by Django 5.0.4 on 2025-05-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("overview", models.TextField(blank=True)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("homepage", models.URLField(blank=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("original_language", models.CharField(blank=True, max_length=10)),
                ("budget", models.BigIntegerField(blank=True, null=True)),
                ("revenue", models.BigIntegerField(blank=True, null=True)),
                ("popularity", models.FloatField(default=0.0)),
                ("vote_average", models.FloatField(default=0.0)),
                ("vote_count", models.IntegerField(default=0)),
                ("poster_path", models.CharField(blank=True, max_length=200)),
                ("backdrop_path", models.CharField(blank=True, max_length=200)),
                ("imdb_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "facebook_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instagram_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("twitter_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "genres",
                    models.ManyToManyField(related_name="movies", to="movies.genre"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TVShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("first_air_date", models.DateField(blank=True, null=True)),
                ("last_air_date", models.DateField(blank=True, null=True)),
                (
                    "episode_run_time",
                    models.IntegerField(
                        blank=True, help_text="Ort. bölüm süresi (dakika)", null=True
                    ),
                ),
                ("number_of_seasons", models.IntegerField(default=0)),
                ("number_of_episodes", models.IntegerField(default=0)),
                ("homepage", models.URLField(blank=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("original_language", models.CharField(blank=True, max_length=10)),
                ("popularity", models.FloatField(default=0.0)),
                ("vote_average", models.FloatField(default=0.0)),
                ("vote_count", models.IntegerField(default=0)),
                ("poster_path", models.CharField(blank=True, max_length=200)),
                ("backdrop_path", models.CharField(blank=True, max_length=200)),
                ("imdb_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "facebook_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instagram_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("twitter_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "genres",
                    models.ManyToManyField(related_name="tvshows", to="movies.genre"),
                ),
            ],
        ),
    ]
