# Generated by Django 5.1.7 on 2025-05-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('episode_run_time', models.IntegerField(blank=True, help_text='Ort. bölüm süresi (dakika)', null=True)),
                ('number_of_seasons', models.IntegerField(default=0)),
                ('number_of_episodes', models.IntegerField(default=0)),
                ('homepage', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('popularity', models.FloatField(default=0.0)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_count', models.IntegerField(default=0)),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('backdrop_path', models.CharField(blank=True, max_length=200)),
                ('genres', models.ManyToManyField(related_name='tvshows', to='movies.genre')),
            ],
        ),
    ]
