# deployment/docker-compose.yml

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../deployment/.env.backend

  frontend:
    build:
      context: ../frontend/presentation
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./.env.frontend