# deployment/docker-compose.yml

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../deployment/.env.backend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app
    ports:
      - "8080:8080"
    env_file:
      - ./.env.frontend
