"""
Django settings for ai_film project.

Generated by 'django-admin startproject' using Django 5.0.4.
For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-7bgh+hnz#fm*s#_9yw%w!5ij!^$hwvch+6t*y#o^3yqt6)&oaq'
)
DEBUG = True  # Sürekli debug modunda
ALLOWED_HOSTS = ['*']  # Tüm hostlara izin ver
AUTH_USER_MODEL = 'accounts.CustomUser'

# Application definition
INSTALLED_APPS = [
    'corsheaders',            # CORS middleware
    'csp',                    # Content Security Policy
    'rest_framework',         # DRF

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'recommendation',
    'core.apps.CoreConfig',   # RBAC app
    'movies',                 # Movie models and serializers
    'accounts',
    'ai_film',                # Main app
    'chatbot',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',        # <-- en üstte
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',    # CSRF koruma
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai_film.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_film.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Default primary key field type
default_auto_field = 'django.db.models.BigAutoField'

# Third-party API keys
TMDB_API_KEY = os.getenv('TMDB_API_KEY')
TMDB_API_BASE_URL = 'https://api.themoviedb.org/3'
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# --------------------------------------------------
# CSRF Protection (Debug Mode)
# --------------------------------------------------
CSRF_COOKIE_SECURE = False      # HTTP üzerinden gönderilsin
CSRF_COOKIE_HTTPONLY = True     # JS erişimine kapalı
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:5173',
]

# --------------------------------------------------
# CORS Settings
# --------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',     # Vue frontend origin
]
CORS_ALLOW_CREDENTIALS = True    # Cookie ve header'ların gitmesine izin ver

# --------------------------------------------------
# Other Security Settings (Debug Mode)
# --------------------------------------------------
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
X_FRAME_OPTIONS = 'SAMEORIGIN'

# --------------------------------------------------
# Content Security Policy (django-csp >= 4.0)
# --------------------------------------------------
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src':  ("'self'",),
        'style-src':   ("'self'",),
        'img-src':     ("'self'", 'data:'),
        'font-src':    ("'self'",),
    }
}
